package com.nexusfin.equity.enums;

public enum BenefitOrderStatusEnum {
    AGREEMENT_PENDING,
    FIRST_DEDUCT_PENDING,
    FIRST_DEDUCT_SUCCESS,
    FIRST_DEDUCT_FAIL,
    FALLBACK_DEDUCT_PENDING,
    FALLBACK_DEDUCT_SUCCESS,
    FALLBACK_DEDUCT_FAIL,
    EXERCISE_PENDING,
    EXERCISE_SUCCESS,
    EXERCISE_FAIL,
    REFUND_SUCCESS,
    REFUND_FAIL,
    SYNC_PENDING,
    SYNC_SUCCESS,
    SYNC_FAIL
}
